quadrotor/trackers_manager:
  ros__parameters:
    trackers: ["NullTracker", "LineTrackerDistance", "LineTrackerMinJerk"]
    line_tracker_distance/default_v_des: 0.5
    line_tracker_distance/default_a_des: 0.5
    line_tracker_distance/epsilon: 0.1
    line_tracker_min_jerk/default_v_des: 0.5
    line_tracker_min_jerk/default_a_des: 0.3
    line_tracker_min_jerk/default_yaw_v_des: 0.1
    line_tracker_min_jerk/default_yaw_a_des: 0.2
